config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => 'accounts', :controllers => { registrations: 'registrations' }

  resources :users do
    resources :posts
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index', as: 'home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :vibe

  validates :body, length: { :maximum => 120 }, :allow_blank => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
end

app/models/vibe.rb
class Vibe < ApplicationRecord
  has_many :posts
  attr_accessor :vibe_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :warning, :danger, :info
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :prepare_vibes
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index

    if params[:search].present?
      search = params[:search]
      @posts = Post.where("body LIKE ?", "%#{search}%")
    else
      @posts = Post.all.order("created_at DESC")
    end

    # @user = User.find(params[:user_id]).name
  end


  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
    @maximum_length = Post.validators_on( :body ).first.options[:maximum]
  end

  # GET /posts/1/edit
  def edit
    @maximum_length = Post.validators_on( :body ).first.options[:maximum]
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_post_path(@post.user.id, @post.id), success: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to user_post_path(@post.user.id, @post.id), success: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_posts_path, success: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def prepare_vibes
      @vibes = Vibe.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:vibe_id, :body)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, message| %>
  <div class="flash-message flash-message-<%= name %> alert alert-<%= name %>">
     <%= message %> <!-- stored in cookie. adds some persistence -->
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" style="border-radius:0px;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= home_path %>"><span class="glyphicon glyphicon-fire" aria-hidden="true"></span>frank</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <!-- <li class="active"><a href="/">Home <span class="sr-only">(current)</span></a></li> -->
        <!-- <li><a href="/about">About</a></li> -->

        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Test<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>Test</li>

          </ul>
        </li> -->
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><a href="<%= user_posts_path(current_user) %>">Hello <%= current_user.name %>!</a></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to 'Login', new_user_session_path %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frank</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <%= render "layouts/messages" %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container col-md-6">
  <h1>New Post</h1>
  <%= form_for post, url: {action: "create"} do |f| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <fieldset class="form-group">
      <%= f.label :vibe %>
      <%= f.collection_select(:vibe_id, @vibes, :id, :name, required: true) %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.text_area :body, class:"form-control", maxlength: @maximum_length, id: 'post_body' %>
      <span id="counter" data-maximum-length="<%= @maximum_length %>"><%= @maximum_length %></span> characters remaining
    </fieldset>

    <fieldset class="actions">
      <% if current_page?(new_user_post_path) %>
      <%= f.submit "Create Post", class:"btn btn-default btn-confirm" %>
      <% else %>
      <%= f.submit "Update Post", class:"btn btn-default btn-confirm" %>
      <% end %>
    </fieldset>
  <% end %>

  <a href="<%= home_path %>" class="btn btn-default btn-back">Back
  </a>

<!-- Character countdown -->
<% asset_path 'post_limit_countdown.js' %>

</div>

app/views/posts/edit.html.erb
<div class="container col-md-6">
  <h1>Edit Post</h1>
  <%= form_for @post, url: {action: "update"} do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <fieldset class="form-group">
      <%= f.label :vibe %>
      <%= f.collection_select(:vibe_id, @vibes, :id, :name, required: true) %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.text_area :body, class:"form-control", maxlength: @maximum_length, id: 'post_body' %>
      <span id="counter" data-maximum-length="<%= @maximum_length %>"><%= @maximum_length %></span> characters remaining
    </fieldset>

    <fieldset class="actions">
      <% if current_page?(new_user_post_path) %>
      <%= f.submit "Create Post", class:"btn btn-default btn-confirm" %>
      <% else %>
      <%= f.submit "Update Post", class:"btn btn-default btn-confirm" %>
      <% end %>
    </fieldset>
  <% end %>

  <a href="<%= home_path %>" class="btn btn-default btn-back">Back
  </a>

<!-- Character countdown -->
<% asset_path 'post_limit_countdown.js' %>

</div>

app/views/posts/index.html.erb
<div class="row">

<div class="page col-md-8 col-md-offset-2">

  <p>
  <% if user_signed_in? %>
    <a href="<%= new_user_post_path(current_user) %>" class='btn btn-default btn-confirm btn-wide'><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>New Post</a>
  <% end %>
  </p>

  <!-- SEARCH BAR -->
  <form class="input-group searchform center has-feedback" action="<%= home_path %>" method="get"x>
    <%= text_field_tag :search, params[:search], class: "searchfield form-control", placeholder: "🔎  Search Posts", required: true %>
    <span class="input-group-btn">
      <%= submit_tag "Search", class: 'btn btn-default btn-search' %>
    </span>
  </form><!-- SEARCH BAR -->

  <br>
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <!-- <div class="panel-heading"></div> -->

    <!-- <div class="panel-body">

    </div> -->

    <!-- Table -->
    <table class="table table-hover">
      <!-- <thead>
        <tr>
          <th colspan="1"><h5>Vibe</h5></th>
          <th colspan="1"><h5>Post</h5></th>
          <th colspan="1"><h5>User</h5></th>
          <th colspan="3"></th>
        </tr>
      </thead> -->
      <tbody>

        <% @posts.each do |post| %>
          <tr>
            <td class="vibe-<%= post.vibe.id %>"></td>
            <td class="td-post"><p><%= post.body %></p><span class="timestamp"><span class="glyphicon glyphicon-user" aria-hidden="true"></span><a href="<%= user_posts_path(post.user) %>"><%= post.user.name %></a>  <span class="glyphicon glyphicon-time" aria-hidden="true"></span><%= time_ago_in_words(post.created_at) %> ago</span></td>
            <% if post.user != current_user %>
            <td><span class="glyphicon glyphicon-pencil inactive" aria-hidden="true"></span></td>
            <td><span class="glyphicon glyphicon-trash inactive" aria-hidden="true"></span></td>
            <% end %>

            <!-- Post Owner Actions -->
            <% if post.user == current_user %>
            <td><a href="<%= edit_user_post_path(post.user.id, post.id) %>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
            <td><a href="<%= user_post_path(post.user.id, post.id) %>" data-method="delete" onclick="return confirm('Are you sure?')"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a></td>
            <% end %>
          </a></tr>
        <% end %>

      </tbody>
    </table>
  </div>

</div>

</div>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="row page">
  <div class="col-md-8 col-md-offset-2">
    <div class="vibe-<%= @post.vibe.id %> post">
      <h4><%= @post.body %>
      </h4>

      <p>
        <strong>by</strong>
        <%= @post.user.name %>
      </p>
    </div>

    <% if current_user == @post.user %>
    <a href="<%= edit_user_post_path(@post) %>" class="btn btn-default btn-back">Edit
    </a>
    <% end %>
    <a href="<%= home_path %>" class="btn btn-default btn-back">Done
    </a>

  </div>
</div>